### PR TITLE
early version of woolfe street scraper

### PR DESCRIPTION
**Pull request by hethcox**
Dan,

The Woolfe Street site does not parse well. The attached pull request handles what is currently there, but there are some coming shows that will need some tweaking. For instance, one of the shows in October is listed as "October X through October Y" but it's not every day during that span so I'm hoping it'll be more specific closer to the show. Anyhoo, take a look and let me know what you think.

-John

PS: I just noticed that I didn't remove the commented out code in index.js.

### CODE REVIEW

**Comment by DanHanf** [comment]
Hey John!

Sorry for the late reply; I've been away from the internet for the weekend. I'll check this all out and let you know!

Thanks,
Dan

**Comment by hethcox** [comment]
Thx. ttyl

**Comment by DanHanf** [comment]
Hey John,

A few comments:
1. It looks like the year is hardcoded at 2015 in woolfe.js. It works for now, but it requires being manually updated every year, which isn't ideal. It would definitely be better for chs-tonight if we could grab a year for each show.
2. Days must be in DD format, meaning a single digit date would be represented as '02' or '04', etc. At the moment, in woolfe.js, a single digit date is represented as '2' or '4', etc.
3. It would be really great to figure out a way to have runs of shows show up for every night of the run.

Other than that, everything looks pretty good! If you can get those three things worked out, Woolfe Street will be up and running!

Let me know if you run into any problems. 

Thanks,
Dan

**Comment by hethcox** [comment]
Thanks Dan,

Now that I understand your site a little better I think the ticketing page
will be much better though I'll have to rewrite the parser. The main site
describes shows as going from "October 2 to October 17" whereas the ticket
site enumerates which dates the show is on.

Here's the link I should have used:
http://woolfestreetplayhouse.tix.com/Schedule.aspx?OrgNum=1687&Tooltip=N

Back to the drawing board...but shouldn't take too long.

Cheers,
John

**Comment by DanHanf** [comment]
Oh nice! Yeah, that page looks like it would be way more useful for what we're trying to do. Thanks a lot!

**Pull request closed without merging**
